name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: >
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.event == 'release'
      }}

    steps:
      - name: Checkout repo at SHA
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Check if commit is on continuous-deployment branch
        id: branch-check
        run: |
          git fetch origin continuous-deployment
          if git merge-base --is-ancestor origin/continuous-deployment HEAD; then
            echo "on_branch=true" >> $GITHUB_OUTPUT
          else
            echo "on_branch=false" >> $GITHUB_OUTPUT
          fi

      - name: Stop if not from continuous-deployment branch
        if: steps.branch-check.outputs.on_branch != 'true'
        run: |
          echo "This release is not from continuous-deployment branch. Skipping deploy."
          exit 1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get the date
        run: echo "date=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eventhub:latest,${{ secrets.DOCKERHUB_USERNAME }}/eventhub:${{ env.date }}

      - name: Deploy to Render
        run: curl ${{ secrets.RENDER_HOOK }}
