name: CI Pipeline

on:
  release:
    types: [published]

jobs:
  build:
    if: github.event.release.target_commitish == 'continuous-deployment'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build
        run: |
          python manage.py check
          python manage.py collectstatic --noinput

  unit-integration-tests:
    if: github.event.release.target_commitish == 'continuous-deployment'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python manage.py test app.test.test_unit

      - name: Run integration tests
        run: |
          python manage.py test app.test.test_integration

  e2e-tests:
    if: github.event.release.target_commitish == 'continuous-deployment'
    needs: unit-integration-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          playwright install

      - name: Run E2E tests
        run: |
          python manage.py test app.test.test_e2e
